[package]
name = "scan2"
description = "Some helpers to get the next items from an underlying stream."
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/purs3lab/scan2"

[dependencies]
